dbt_investment_FAR_TRANS:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed' # Replace with your Snowflake account identifier
      
      # User authentication
      user: DGOH
      
      # Database configuration
      role: FAR_TRANS_DBT_ROLE
      database: FAR_TRANS_DB
      warehouse: FAR_TRANS_WH
      schema: RAW
      
      # Connection parameters
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_far_trans
      
    prod:
      type: snowflake
      account: 'not needed' # Replace with your Snowflake account identifier
      
      # User authentication
      user: DGOH
      password: 'not needed' # Replace with actual password
      
      # Database configuration
      role: FAR_TRANS_DBT_ROLE
      database: FAR_TRANS_DB
      warehouse: FAR_TRANS_WH
      schema: RAW
      
      # Connection parameters
      threads: 8
      client_session_keep_alive: True
      query_tag: dbt_far_trans_prod
