version: 2

sources:
  - name: raw
    database: FAR_TRANS_DB
    schema: raw
    tables:
      - name: asset_information
        description: Raw asset information data
        columns:
          - name: isin
            description: International Securities Identification Number
            tests:
              - not_null
              - unique
          - name: assetname
            description: Full name of the asset
            tests:
              - not_null
          - name: assetcategory
            description: Category of the asset (Stock, Bond, MTF)
            tests:
              - not_null
              - accepted_values:
                  values: ['Stock', 'Bond', 'MTF']
          - name: assetshortname
            description: Short name/symbol of the asset
          - name: assetsubcategory
            description: Sub-category of the asset
          - name: marketid
            description: Market identifier
          - name: sector
            description: Business sector
          - name: industry
            description: Specific industry
          - name: timestamp
            description: Record validity timestamp

      - name: close_prices
        description: Daily closing prices for assets
        columns:
          - name: isin
            description: International Securities Identification Number
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'asset_information')
                  field: isin
          - name: timestamp
            description: Price date
            tests:
              - not_null
          - name: closeprice
            description: Closing price
            tests:
              - not_null
              - positive_close_prices

      - name: customer_information
        description: Customer profile and risk information
        columns:
          - name: customerid
            description: Unique customer identifier
            tests:
              - not_null
              - unique
          - name: customertype
            description: Type of customer (Premium, Mass)
            tests:
              - not_null
              - accepted_values:
                  values: ['Premium', 'Mass']
          - name: risklevel
            description: Customer's risk tolerance level
            tests:
              - not_null
              - valid_risk_level
          - name: investmentcapacity
            description: Investment capacity category
            tests:
              - not_null
              - accepted_values:
                  values: 
                    - 'Predicted_CAP_LT30K'
                    - 'CAP_30K_80K'
                    - 'CAP_80K_300K'
                    - 'CAP_300K_1M'
                    - 'CAP_GT1M'
          - name: lastquestionnairedate
            description: Date of last risk questionnaire completion
          - name: timestamp
            description: Record validity timestamp

      - name: transactions
        description: Customer transaction data
        columns:
          - name: customerid
            description: Customer identifier
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'customer_information')
                  field: customerid
          - name: isin
            description: International Securities Identification Number
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'asset_information')
                  field: isin
          - name: transactionid
            description: Unique transaction identifier
            tests:
              - not_null
              - unique
          - name: transactiontype
            description: Type of transaction (Buy, Sell)
            tests:
              - not_null
              - accepted_values:
                  values: ['Buy', 'Sell']
          - name: timestamp
            description: Transaction date
            tests:
              - not_null
          - name: totalvalue
            description: Total transaction value
            tests:
              - not_null
          - name: units
            description: Number of units traded
            tests:
              - not_null
          - name: channel
            description: Transaction channel
          - name: marketid
            description: Market identifier

models:
  - name: stg_asset_information
    description: Standardized asset information
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - isin
            - valid_from
    columns:
      - name: isin
        tests:
          - not_null
          - unique

  - name: stg_close_prices
    description: Standardized close prices
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - isin
            - price_date
    columns:
      - name: close_price
        tests:
          - not_null
          - positive_close_prices

  - name: stg_customer_information
    description: Standardized customer information
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_id
            - valid_from
    columns:
      - name: risk_level
        tests:
          - valid_risk_level

  - name: stg_transactions
    description: Standardized transaction data
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: isin
        tests:
          - not_null