version: 2

sources:
  - name: raw
    database: FAR_TRANS_DB
    schema: raw
    tables:
      - name: asset_information
        description: Raw asset information data
        columns:
          - name: isin
            description: International Securities Identification Number
            tests:
              - not_null
              - unique
              - dbt_expectations.expect_column_value_lengths_to_equal:
                  value: 12
          - name: assetname
            description: Full name of the asset
            tests:
              - not_null
          - name: assetcategory
            description: Category of the asset (Stock, Bond, MTF)
            tests:
              - not_null
              - accepted_values:
                  values: ['Stock', 'Bond', 'MTF']

      - name: close_prices
        description: Daily closing prices for assets
        columns:
          - name: isin
            description: International Securities Identification Number
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'asset_information')
                  field: isin
          - name: timestamp
            description: Price date
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: '2018-01-01'
                  max_value: '2025-12-31'
          - name: closeprice
            description: Closing price
            tests:
              - not_null
              - positive_close_prices

      - name: customer_information
        description: Customer profile and risk information
        columns:
          - name: customerid
            description: Unique customer identifier
            tests:
              - not_null
              - unique
          - name: customertype
            description: Type of customer (Premium, Mass)
            tests:
              - not_null
              - accepted_values:
                  values: ['Premium', 'Mass']
          - name: risklevel
            description: Customer's risk tolerance level
            tests:
              - not_null
              - valid_risk_level
          - name: investmentcapacity
            description: Investment capacity category
            tests:
              - not_null
              - accepted_values:
                  values: 
                    - 'Predicted_CAP_LT30K'
                    - 'CAP_30K_80K'
                    - 'CAP_80K_300K'
                    - 'CAP_300K_1M'
                     - 'CAP_GT1M'

      - name: markets
        description: Market reference data
        columns:
          - name: exchangeID
            description: Exchange identifier
            tests:
              - not_null
          - name: marketID
            description: Market identifier
            tests:
              - not_null
          - name: name
            description: Market name
          - name: description
            description: Market description
          - name: country
            description: Country where market operates
          - name: tradingDays
            description: Trading days of the week
          - name: tradingHours
            description: Trading hours
          - name: marketClass
            description: Market classification

      - name: limit_prices
        description: Price limits for assets
        columns:
          - name: isin
            description: International Securities Identification Number
            tests:
              - not_null
          - name: timestamp
            description: Price date
          - name: upper_limit
            description: Upper price limit
          - name: lower_limit
            description: Lower price limit
          - name: currency
            description: Currency

      - name: questionnaire
        description: Customer questionnaire responses
        columns:
          - name: questionnaire_id
            description: Unique questionnaire identifier
            tests:
              - not_null
          - name: customer_id
            description: Customer identifier
            tests:
              - not_null
          - name: submission_date
            description: When questionnaire was submitted
          - name: investment_horizon
            description: Investment time horizon
          - name: risk_tolerance_score
            description: Risk tolerance score
          - name: investment_knowledge
            description: Investment knowledge level
          - name: income_bracket
            description: Income bracket
          - name: investment_goal
            description: Investment goal
          - name: loss_tolerance
            description: Loss tolerance percentage
          - name: preferred_investment_types
            description: Preferred investment types
          - name: timestamp
            description: Record timestamp

models:
  - name: stg_asset_information
    description: Standardized asset information
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - isin
            - valid_from
    columns:
      - name: isin
        tests:
          - not_null
          - unique

  - name: stg_close_prices
    description: Standardized close prices
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - isin
            - price_date
    columns:
      - name: close_price
        tests:
          - not_null
          - positive_close_prices

  - name: stg_customer_information
    description: Standardized customer information
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_id
            - valid_from
    columns:
      - name: risk_level
        tests:
          - valid_risk_level